//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemMobile.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendingMachines
    {
        public int VendingMachineId { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public string Modem { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> IntervalService { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public string StatusMachine { get; set; }
        public string StatusService { get; set; }
        public string NameUser { get; set; }
        public string Priority { get; set; }
    }
}
