//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemWeb.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewId { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
    }
}
