//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemWeb.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistories
    {
        public int StatusHistoryId { get; set; }
        public Nullable<int> VendingMachineId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
