//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int VendingMachineId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
        public decimal TotalSum { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int PaymentTypeId { get; set; }
    
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual Products Products { get; set; }
        public virtual VendingMachines VendingMachines { get; set; }
    }
}
