//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendingMachines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendingMachines()
        {
            this.Events = new HashSet<Events>();
            this.Sales = new HashSet<Sales>();
            this.Services = new HashSet<Services>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Model { get; set; }
        public int MachineTypeId { get; set; }
        public decimal TotalProfit { get; set; }
        public string SerialNumber { get; set; }
        public string InventoryNumber { get; set; }
        public string Manufacturer { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime LastCheckDate { get; set; }
        public int InterCheckMonth { get; set; }
        public int ResourceHour { get; set; }
        public System.DateTime NextCheckDate { get; set; }
        public int ServiceTime { get; set; }
        public int StatusId { get; set; }
        public int CountryId { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CompanyId { get; set; }
        public int ModemId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        public virtual MachineStatuses MachineStatuses { get; set; }
        public virtual MachineTypes MachineTypes { get; set; }
        public virtual Modems Modems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
