//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingSystemWPF.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Id { get; set; }
        public int VendingMachineId { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string Description { get; set; }
        public string Problems { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual VendingMachines VendingMachines { get; set; }
    }
}
